#!/bin/bash

MY_PATH=${BASH_SOURCE%/*}

[[ -x $MY_PATH/calc-versions.txt ]] || cp $MY_PATH/../master/calc-versions.txt .
[[ -d $MY_PATH/schema ]] || cp -R $MY_PATH/../../schema/resources/schema .

node $MY_PATH/cli.js $@
